server:
   port: 9091

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/auth/realms/ssd-exam-realm/protocol/openid-connect/certs
      